name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build and Push Docker Image
      run: |
        docker build -t sachinkn92/devops-app .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u sachinkn92 --password-stdin
        docker push sachinkn92/devops-app

    - name: Deploy to EKS
      run: |
        aws eks --region us-east-1 update-kubeconfig --name devops-cluster
        kubectl apply -f k8s-deployment.yml
        kubectl apply -f k8s-service.yml