name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t sachinkn92/devops-app .
    
    - name: Check for tests
      run: |
        if [ -f app/package.json ] && grep -q '"test":' app/package.json; then
          echo "Running tests..."
          docker run sachinkn92/devops-app npm test
        else
          echo "No tests configured - skipping"
        fi